[package]
name = "chibircc"
version = "0.1.0"
authors = ["Robin Moussu <moussu.robin@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2.33.3"
color-eyre = "^0.5.6"
eyre = "^0.6.2"
